---
title: "Lista 2"
author: "Felipe Manzi"
date: "04/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Exercício 1:

Funções
```{r cars}
x <- 1
b <- 2
d <- 3
y <- 40
z <- 20
abs(x)
sqrt(x)
exp(x)
log(x)
log(x, b)
round(x, d)
factorial(x)
seq(x, y, z)
```

Operadores
```{r pressure, echo=FALSE}
3 + 2 == 5
-2 < 10 + 1
2 > 9 * 3
2 >=  2.5 + 2.5
2 <= 1 + 3
2 != 1.5 + 0
TRUE | FALSE
TRUE & FALSE
```

Exercício 2:
```{r}
x <- 1
b <- 2
d <- 3
y <- 40
z <- 20
curve(abs(x),from = 0, to = 5 )
curve(sqrt(x),from = 0, to = 5 )
curve(exp(x),from = 0, to = 5 )
curve(log(x),from = 0, to = 5 )
curve(log(x, b),from = 0, to = 5 )
curve(round(x, d),from = 0, to = 5 )
curve(factorial(x),from = 0, to = 5 )
```

Exercício 3:
```{r}
vector_numerical <- c(5, 4, 3)
print(vector_numerical)
class(vector_numerical)
  
vector_character <- c("a", "b", "c")
print(vector_character)
class(vector_character)
  
vector_logical <- c(T, F, F)
print(vector_logical)
class(vector_logical) 
  
vector_complex <- c(1 + 2i, 3i, 3i)
print(vector_complex)
class(vector_complex) 
  
vector_factor <- as.factor(c(1, 1, 2, 3))
print(vector_factor)
class(vector_factor) 
```
Exercício 4:

```{r}
library(readxl)
populacao_estimada <- read_excel("C:/Users/usuario/Downloads/População estimada dos municípios.xlsx")
#para visualizar a cabeça(o "head")
head(populacao_estimada)
```
Exercício 5:

```{r}
class(populacao_estimada)
dim(populacao_estimada)
nrow(populacao_estimada)
ncol(populacao_estimada)
names(populacao_estimada)
head(populacao_estimada)
str(populacao_estimada)
colMeans(populacao_estimada[c(4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21)])
summary(populacao_estimada)
```
